#!/bin/bash

bookmark="$(pbpaste)"
file="$HOME/Library/Mobile Documents/com~apple~CloudDocs/bookmarks.txt"

if grep -q "^$bookmark$" "$file"; then
	terminal-notifier -title 'bookie.sh - Geep!' -message 'You already bookmarked this!'
else
	echo " " >> "$file"
	echo $bookmark >> "$file"
	terminal-notifier -title 'bookie.sh - Tada!' -message $bookmark+=' bookmarked'
fi
