#!/bin/bash
#Bookie Surf

file="$HOME/Configs/bookmarks.txt"
website=$(cat "$file" | fzf --reverse)
browser="safari"

url=$(echo "$website" | sed 's/#.*//' | sed 's/\s//')

if [ -z "$url" ]; then
	terminal-notifier -title 'Bookie Surf - geep!' -message "You have not selected a website!"
else	
	open -a $browser $url
fi