#!/bin/sh

# Move To Configs Folder
cd ~/Configs

# Export Brew List
brew bundle dump

# Run Shortcut to get timestamp
shortcuts run "FileStamp"

# Open Configs for labeling
mv Brewfile "BrewFile_$(pbpaste)"

# DEBUG: Open to Confirm All's Goed
open .